package com.myspace.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class cb_user_summary implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String cbplus_membership_group;

	private java.lang.Boolean is_blacklisted_user;

	public cb_user_summary() {
	}

	public java.lang.String getCbplus_membership_group() {
		return this.cbplus_membership_group;
	}

	public void setCbplus_membership_group(
			java.lang.String cbplus_membership_group) {
		this.cbplus_membership_group = cbplus_membership_group;
	}

	public java.lang.Boolean getIs_blacklisted_user() {
		return this.is_blacklisted_user;
	}

	public void setIs_blacklisted_user(java.lang.Boolean is_blacklisted_user) {
		this.is_blacklisted_user = is_blacklisted_user;
	}

	public cb_user_summary(java.lang.String cbplus_membership_group,
			java.lang.Boolean is_blacklisted_user) {
		this.cbplus_membership_group = cbplus_membership_group;
		this.is_blacklisted_user = is_blacklisted_user;
	}

}