package com.myspace.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class cdp_user implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String _id;

	private com.myspace.myproject.user_gameplan user_gameplan;

	private com.myspace.myproject.cb_user_summary cb_user_summary;

	private com.myspace.myproject.user_summary user_summary;

	public cdp_user() {
	}

	public java.lang.String get_id() {
		return this._id;
	}

	public void set_id(java.lang.String _id) {
		this._id = _id;
	}

	public com.myspace.myproject.user_gameplan getUser_gameplan() {
		return this.user_gameplan;
	}

	public void setUser_gameplan(
			com.myspace.myproject.user_gameplan user_gameplan) {
		this.user_gameplan = user_gameplan;
	}

	public com.myspace.myproject.cb_user_summary getCb_user_summary() {
		return this.cb_user_summary;
	}

	public void setCb_user_summary(
			com.myspace.myproject.cb_user_summary cb_user_summary) {
		this.cb_user_summary = cb_user_summary;
	}

	public com.myspace.myproject.user_summary getUser_summary() {
		return this.user_summary;
	}

	public void setUser_summary(com.myspace.myproject.user_summary user_summary) {
		this.user_summary = user_summary;
	}

	public cdp_user(java.lang.String _id,
			com.myspace.myproject.user_gameplan user_gameplan,
			com.myspace.myproject.cb_user_summary cb_user_summary,
			com.myspace.myproject.user_summary user_summary) {
		this._id = _id;
		this.user_gameplan = user_gameplan;
		this.cb_user_summary = cb_user_summary;
		this.user_summary = user_summary;
	}

}