package com.myspace.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class myObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer age;
	private java.lang.Float salary;
	private java.lang.Boolean isEligible;
	public myObject() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Float getSalary() {
		return this.salary;
	}

	public void setSalary(java.lang.Float salary) {
		this.salary = salary;
	}

	public java.lang.Boolean getIsEligible() {
		return this.isEligible;
	}

	public void setIsEligible(java.lang.Boolean isEligible) {
		this.isEligible = isEligible;
	}

	public myObject(java.lang.Integer age, java.lang.Float salary,
			java.lang.Boolean isEligible) {
		this.age = age;
		this.salary = salary;
		this.isEligible = isEligible;
	}

}