package com.myspace.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class user_gameplan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> focus_area_keys;

	public user_gameplan() {
	}

	public java.util.List<java.lang.String> getFocus_area_keys() {
		return this.focus_area_keys;
	}

	public void setFocus_area_keys(
			java.util.List<java.lang.String> focus_area_keys) {
		this.focus_area_keys = focus_area_keys;
	}

	public user_gameplan(java.util.List<java.lang.String> focus_area_keys) {
		this.focus_area_keys = focus_area_keys;
	}

}