package com.myspace.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class user_summary implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean is_icwb_membership;

	public user_summary() {
	}

	public java.lang.Boolean getIs_icwb_membership() {
		return this.is_icwb_membership;
	}

	public void setIs_icwb_membership(java.lang.Boolean is_icwb_membership) {
		this.is_icwb_membership = is_icwb_membership;
	}

	public user_summary(java.lang.Boolean is_icwb_membership) {
		this.is_icwb_membership = is_icwb_membership;
	}

}